<?php

return [
    'throttle' => 5,
    'admin' => 1,
    'user' => 2,
    'pagination' => 10,
    'block' => 1,
    'active' => 0,
    'memory' => [
        '8GB',
        '16GB',
        '32GB',
        '64GB',
        '128GB',
        '256GB',
        '512GB',
        '1TB',
    ],
    'color' => [
        'white',
        'pink',
        'purple',
        'red',
        'orange',
        'yellow',
        'gold',
        'green',
        'cyan',
        'blue',
        'brown',
        'grey',
        'silver',
    ],
    'pending' => 0,
    'approve' => 1,
    'reject' => 2,
    'one_stars' => 1,
    'two_stars' => 2,
    'three_stars' => 3,
    'four_stars' => 4,
    'five_stars' => 5,
    'percent' => 100,
    'twelve' => 12,
    'pink_color' => 'rgb(255, 99, 132)',
];
